# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: "gateway-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
    - name: "database-port"
      protocol: "TCP"
      port: 10000
      targetPort: 10000